### ISSUE TITLE
InternalBot.js error when running extension

### ISSUE THREAD

**Issue by GilbertGobbels** [BitQuote/AwesomeBot-Neo#1]
When trying to use bot.handleViolation, a TypeError is thrown.
It looks like some stupid JS error, shouldn't be too hard to fix?
https://gyazo.com/dd8da05bf12c33b6f481df86934286e0
Line 75: `if(!member.user.bot) {`

**Comment by BitQuote** [comment]
`bot.handleViolation(ch, member, userMessage, adminMessage, strikeMessage, action, roleid)`

You need to pass a [Member](https://abal.moe/ErisDev/Member.html), not a user or ID.
