### ISSUE TITLE
Clan (clanwar, clansetup) module

### ISSUE THREAD

**Issue by pedall** [BitQuote/AwesomeBot-Neo#18]
- [ ] Clans can be created / edited / deleted (Titel, custom clan emoji name, respective discord role of the clan, clan leader and his respective role, cw manager and his respective role)
- [ ] clan leader gets assigned by bot admin (or via role)
- [ ] cw manager(s) per clan can be assigned by clan leader and bot admins
- [ ] clan members can be added / deleted via chat command to a clan (role gets assigned automatically) (can be added by clan leader and bot admin)
- [ ] clan war events can be created for future clanwars (via gaming event module)
- [ ] cw tracking via chat cmd and / or UI (!cw result clan1 clan2 10:5) (only executable from cw managers / clan leaders / bot admins)
- [ ] cw stats via command and / or UI (!cw stats shows last 10 matches in general, !cw stats clan1 shows last 10 matches of that clan)
- [ ] leaderboard via chat command and / or UI (incl. admin option to start a new season)

**Comment by BitQuote** [comment]
probably better suited for an extension
