### ISSUE TITLE
bot.handleViolation doesn't seem to give a strike

### ISSUE THREAD

**Issue by GilbertGobbels** [BitQuote/AwesomeBot-Neo#2]
Yes;
function is given a valid channel, member object, userMsg, adminMsg, and reason.
Tried with both action "none" and "strike" (I know the last one doesn't exist.).
RoleID is not given, but shouldn't make a difference.
The rest of handleViolation (message User, message Admin, etc.) seems to work fine. But the strike doesn't appear in the strikes list, nor in the actual server config.

Let's hope this is not me being stupid again xS

**Comment by BitQuote** [comment]
Fix will roll out shortly.
