### ISSUE TITLE
extended help for reload command irritating

### ISSUE THREAD

**Issue by pedall** [BitQuote/AwesomeBot-Neo#28]
title says pm command

extended help says pm or public

![image](https://cloud.githubusercontent.com/assets/20089354/19309781/4509b7ea-9087-11e6-8f85-22b26bd5d8ad.png)

**Comment by Kays** [comment]
I doubt it's a big problem anyway because `reload` is a maintainer-only command. ;)

**Comment by GilbertGobbels** [comment]
I think it means it's a command to use in PM, but you can choose to reload either public or pm commands. Will have to check.

**Comment by GilbertGobbels** [comment]
Confirmed in /Commands/PM/reload.js
