### ISSUE TITLE
After bot restart, extension code seems to be dumped

### ISSUE THREAD

**Issue by GilbertGobbels** [BitQuote/AwesomeBot-Neo#3]
After Neo bot restarted earlier today, not only my server-local extension's code got dumped (emptied), the code published to the gallery vanished aswell. However, the extension metadata is still intact (name, trigger, type, etc.)

Might just happen at random, or only after bot restart. Not really sure.

This happens with the public bot, haven't tested on self-hosted version, and I most likely won't.

**Comment by BitQuote** [comment]
OpenShi~~f~~t bug 😕
